"""initial_schema

Revision ID: a2caaccfb60e
Revises: 
Create Date: 2026-04-09 12:22:37.964557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a2caaccfb60e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('full_name', sa.String(length=256), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('athlete_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('sport_type', sa.String(length=32), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('resting_heart_rate_bpm', sa.Integer(), nullable=False),
    sa.Column('maximum_heart_rate_bpm', sa.Integer(), nullable=False),
    sa.Column('functional_threshold_power', sa.Integer(), nullable=True),
    sa.Column('current_vo2max', sa.Float(), nullable=True),
    sa.Column('training_experience_years', sa.Integer(), nullable=False),
    sa.Column('weekly_target_hours', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('performance_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('athlete_profile_id', sa.Uuid(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estimated_vo2max', sa.Float(), nullable=False),
    sa.Column('heart_rate_zones', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('lactate_threshold_pace_sec_per_km', sa.Integer(), nullable=True),
    sa.Column('chronic_training_load', sa.Float(), nullable=False),
    sa.Column('acute_training_load', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_profile_id'], ['athlete_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('athlete_profile_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('goal_description', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('sport_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['athlete_profile_id'], ['athlete_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_blocks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('training_plan_id', sa.Uuid(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=32), nullable=False),
    sa.Column('target_weekly_distance_meters', sa.Integer(), nullable=False),
    sa.Column('target_weekly_duration_seconds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['training_plan_id'], ['training_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('athlete_profile_id', sa.Uuid(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('session_type', sa.String(length=32), nullable=False),
    sa.Column('training_block_id', sa.Uuid(), nullable=True),
    sa.Column('target_distance_meters', sa.Integer(), nullable=True),
    sa.Column('target_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('target_min_pace_sec_per_km', sa.Integer(), nullable=True),
    sa.Column('target_max_pace_sec_per_km', sa.Integer(), nullable=True),
    sa.Column('target_heart_rate_zone', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['athlete_profile_id'], ['athlete_profiles.id'], ),
    sa.ForeignKeyConstraint(['training_block_id'], ['training_blocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workout_session_id', sa.Uuid(), nullable=False),
    sa.Column('athlete_profile_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_distance_meters', sa.Integer(), nullable=False),
    sa.Column('actual_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('average_pace_sec_per_km', sa.Integer(), nullable=False),
    sa.Column('average_heart_rate_bpm', sa.Integer(), nullable=True),
    sa.Column('maximum_heart_rate_bpm', sa.Integer(), nullable=True),
    sa.Column('perceived_exertion', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_profile_id'], ['athlete_profiles.id'], ),
    sa.ForeignKeyConstraint(['workout_session_id'], ['workout_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workout_session_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_logs')
    op.drop_table('workout_sessions')
    op.drop_table('training_blocks')
    op.drop_table('training_plans')
    op.drop_table('performance_metrics')
    op.drop_table('athlete_profiles')
    op.drop_table('users')
    # ### end Alembic commands ###
